name: Deploy to Dev
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i && npm run build
      - name: Deploy to dev
        run: sudo npm i -g firebase-tools && firebase hosting:channel:deploy dev --token ${{ secrets.FIREBASE_TOKEN }} 